config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :frnds
  # get 'home/index'
  #root 'home#index'
  root 'frnds#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/frnd.rb
class Frnd < ApplicationRecord
	belongs_to:user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable



          has_many:frnds

       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frnds_controller.rb
class FrndsController < ApplicationController
  before_action :set_frnd, only: %i[ show edit update destroy ]
  before_action:authenticate_user!,except:[:index,:show]
  before_action:correct_user,only:[:edit,:update,:destroy]

  # GET /frnds or /frnds.json
  def index
    @frnds = Frnd.all
  end

  # GET /frnds/1 or /frnds/1.json
  def show
  end

  # GET /frnds/new
  def new
    @frnd = Frnd.new
    # @friend=current_user.frnds.build
end



  # GET /frnds/1/edit
  def edit
  end

  # POST /frnds or /frnds.json
  def create
    @frnd = Frnd.new(frnd_params)
    # @frnd=current_user.frnds.build(frnd_params)
  #end

    respond_to do |format|
      if @frnd.save
        format.html { redirect_to frnd_url(@frnd), notice: "Frnd was successfully created." }
        format.json { render :show, status: :created, location: @frnd }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frnd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frnds/1 or /frnds/1.json
  def update
    respond_to do |format|
      if @frnd.update(frnd_params)
        format.html { redirect_to frnd_url(@frnd), notice: "Frnd was successfully updated." }
        format.json { render :show, status: :ok, location: @frnd }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frnd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frnds/1 or /frnds/1.json
  def destroy
    @frnd.destroy

    respond_to do |format|
      format.html { redirect_to frnds_url, notice: "Frnd was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend=current_user.frnds.find_by(id: params[:id])
    redirect_to frnd_path,notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frnd
      @frnd = Frnd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frnd_params
      params.require(:frnd).permit(:first_name, :last_name, :Email, :phone_no, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about 
  end
  # def new
  # @post = Post.new
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frnds_helper.rb
module FrndsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frnds/_form.html.erb
<%= form_with(model: frnd) do |form| %>
  <% if frnd.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(frnd.errors.count, "error") %> prohibited this frnd from being saved:</h2>

      <ul>
        <% frnd.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name,class:"form-control pb-2",placeholder:"FirstName" %>
    <br></br>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :last_name ,class:"form-control",placeholder:"LastName"%>
    <br></br>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :Email ,class:"form-control",placeholder:"Email"%>
    <br></br>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :phone_no,class:"form-control" ,placeholder:"Phone_no"%>
    <br></br>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :twitter,class:"form-control",placeholder:"Twitter" %>
    <br />
  </div>

   <div class="field form-group">
    
    <%= form.text_field :user_id,class:"form-control",id: :friend_user_id,value:current_user.id,type: :hidden %>
    <br />
  </div>

  <div>
    <%= form.submit  class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/frnds/_frnd.html.erb
<div id="<%= dom_id frnd %>">
  <p>
    <strong>First name:</strong>
    <%= frnd.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= frnd.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= frnd.Email %>
  </p>

  <p>
    <strong>Phone no:</strong>
    <%= frnd.phone_no %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= frnd.twitter %>
  </p>

</div>

app/views/frnds/_frnd_details.html.erb
<tr>

      <td><%= link_to frnd.first_name + ' ' + frnd.last_name , frnd %></td>
      
      </td>
      <td><%= frnd.Email %></td>
      <td><%= frnd.phone_no %></td>
      <td><%= frnd.twitter %></td>
      <td><%= frnd.user_id%></td>
      
      <td><%= link_to "Delete", frnd,class:"btn btn-danger btn-sm" %></td>
     
</tr>

app/views/frnds/edit.html.erb
<h1>Editing frnd</h1>

<%= render "form", frnd: @frnd %>

<br>

<div>
  <%= link_to "Show this frnd", @frnd %> |
  <%= link_to "Back to frnds", frnds_path %>
</div>

app/views/frnds/index.html.erb
  <div id="frnds">
<% if user_signed_in? %>
    <table class="table table-hover table-bordere">
    <thead class="table-dark" >
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone_No</th>
        <th scope="col">Twitter</th>
        <th scope="col">user Id</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </thead>
    <tbody>
      <% @frnds.each do |frnd| %>
      <%= render 'frnd_details',frnd:frnd %>
    <% end %>
      
    </tbody>
  </table>

  <%= link_to "New friend", new_frnd_path,class:"btn btn-secondary"%>
  



<% else %>
  <h1>Friend  app</h1>
  <p>rail first project</p>
<% end %>

</div>

app/views/frnds/new.html.erb
<h1>New friend</h1>

<%= render "form", frnd: @frnd %>

<br>

<div>
  <%= link_to "Back to frnds", frnds_path %>
</div>

app/views/frnds/show.html.erb
<%= render @frnd %>

<div >
  <%= link_to "Edit this frnd", edit_frnd_path(@frnd),class:"btn btn-secondary px-2" %> 
  <%= link_to "Back to frnds", frnds_path,class:"btn btn-secondary px-2" %>

  <%= button_to "Destroy this frnd", @frnd, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'FriendApp',root_path,class:'navbar-brand' %>
    

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">


        <li class="nav-item px-2 ">
          <%= link_to 'About us',home_about_path,
      	  class:'nav-item' %>
        </li>

       <!--  <li class="nav-item px-2 ">
          <%#= link_to 'Show Friend',frnds_path,
          class:'nav-item' %>
        </li> -->

        

        
        <%if user_signed_in? %>
          <li class="nav-item px-2  ">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:
          'nav-item' %>
          </li>
         

          <li class="nav-item px-2 ">
          <%= link_to 'ADDFriend',new_frnd_path,
          class:'nav-item' %>
          </li>

           <li class="nav-item pl-10 ">
            <%= link_to 'SignOUT', destroy_user_session_path, :method => :delete, class:'nav-item' %>
          </li>

        <% end %>


         <li class="nav-item px-2 ">
          <%= link_to 'SignUP',new_user_registration_url,
          class:'nav-item' %>
        </li>

        <li class="nav-item px-2 ">
          <%= link_to 'SignIn', new_user_session_path,
          class:'nav-item' %>
        </li>


        

        

       











        
       
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us<h1>

app/views/home/index.html.erb
<h1>Friend  app</h1>
<p>rail first project</p>

app/views/layouts/_alerts.html.erb
<!-- <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> -->

<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <%= flash %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->

    <title>FriendApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%#= javascript_include_tag 'rails' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    
      <%= render 'home/header' %>
      <br><br />
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
    <%= yield %>
   <!--  <h1>Hello, world!</h1> -->
 </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>